site_name: WEB1
site_url: https://kasperknop.github.io/WEB1
theme:
    features:
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        - navigation.top
        - content.code.copy
    name: material
    custom_dir: overrides
    icon:
        logo: material/web
    palette:
        # # Palette toggle for automatic mode
        # - media: "(prefers-color-scheme)"
        #   primary: blue
        #   toggle:
        #       icon: material/brightness-auto
        #       name: Switch to light mode
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: blue
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: blue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

nav:
    - "Introduction": index.md
    - "01 The Web & HTML": 01-the-web-and-html.md
    - "02 CSS": 02-css.md
    - "03 Layout": 03-layout.md
    - "04 First Project": 04-first-project.md
    - "05 Forms": 05-forms.md
    - "06 Web Design": 06-web-design.md
    - "07 Second Project": 07-second-project.md
    - "08 JavaScript": 08-javascript.md
    # - "09 Browser APIs": 09-browser-apis.md
    # - "10 Third Project": 10-third-project.md
    # - "11 Fetching Data": 11-fetching-data.md
    # - "12 Wrap Up": 12-wrap-up.md

extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
