site_name: WEB1
site_url: https://kasperknop.github.io/WEB1
theme:
    features:
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        - navigation.top
    name: material
    icon:
        logo: material/web
    palette:
        # # Palette toggle for automatic mode
        # - media: "(prefers-color-scheme)"
        #   primary: blue
        #   toggle:
        #       icon: material/brightness-auto
        #       name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: blue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: blue
          toggle:
              icon: material/brightness-4
              name: Switch to system preference

markdown_extensions:
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
    - "Introduction": 00-index.md
    - "Web infrastructure & HTML": 01-web-infrastructure-and-html.md
    - "CSS Fundamentals": 02-css-fundamentals.md
    - "Forms & Validation": 03-forms-and-validation.md
    - "First Project": 04-project-1.md
    - "Responsive Layouts": 05-responsive-layouts.md
    - "Web Design for Developers": 06-web-design-for-developers.md
    - "Second Project": 07-project-2.md
    - "JavaScript Fundamentals": 08-javascript-fundamentals.md
    - "The DOM, Events & Storage": 09-the-dom-events-and-storage.md
    - "Data Fetching": 10-data-fetching.md
    - "Third Project": 11-project-3.md
    - "Wrap Up": 12-wrap-up.md

extra_css:
    - stylesheets/extra.css
