site_name: WEB1
site_url: https://kasperknop.github.io/WEB1
theme:
    features:
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        - navigation.top
        - content.code.copy
    name: material
    custom_dir: overrides
    icon:
        logo: material/web
    palette:
        # # Palette toggle for automatic mode
        # - media: "(prefers-color-scheme)"
        #   primary: blue
        #   toggle:
        #       icon: material/brightness-auto
        #       name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: blue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: blue
          toggle:
              icon: material/brightness-4
              name: Switch to system preference

nav:
    - "Introduction": index.md
    - "01 Web infrastructure & HTML": 01-web-infrastructure-and-html.md
    - "02 CSS Fundamentals": 02-css-fundamentals.md
    - "03 Forms & Validation": 03-forms-and-validation.md
    - "04 First Project": 04-first-project.md
    - "05 Responsive Layouts": 05-responsive-layouts.md
    - "06 Web Design for Developers": 06-web-design-for-developers.md
    - "07 Second Project": 07-second-project.md
    - "08 JavaScript Fundamentals": 08-javascript-fundamentals.md
    - "09 The DOM, Events & Storage": 09-the-dom-events-and-storage.md
    - "10 Data Fetching": 10-data-fetching.md
    - "11 Third Project": 11-third-project.md
    - "12 Wrap Up": 12-wrap-up.md

extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
